environment:
  SSL_CERT_FILE: "C:\\OpenSSL\\cacert.pem"

  TEST_APP_ID:
    secure: BxdmP2b27g5X5MtNtrPn//nEU910jKuc35acBP87NutqghfHdcfGs4hzYX+P9kgp
  TEST_APP_SECRET:
    secure: TuKrAyGpAdArLUujhZUrwTYpQCmHv/ZsOL4w+au5b3W16d/UNJbXaZlA4lJVfEYO
  TEST_APP_USER_NAME:
    secure: rBiJxlAihHp810szCSz2v/C4khRkXUFUHjcDibYw5TTCfEfRtS1kwsu2T2cqOaXp
  TEST_APP_PASSWORD:
    secure: h0LX6syLa7EtRVjYBOIbnSe7BA+fka3DBYHPJPrANhw=
  TEST_APP_TENANT:
    secure: UyWna7PmLBrBDldEt3nU8MjvVNWPl0DznY7KQxJHCq7FGmIdf1ZzyV9KWS7Is9fj
  TEST_APP_USER_ID:
    secure: a9Ub4PSHMHvqaTopXIFadzDgeueMah1hMVd1mNiG+JjWEiWUTgI6J1jEvm5PaEHE

  matrix:
    - TARGET: i686-pc-windows-msvc
      BITS: 32

    - TARGET: x86_64-pc-windows-msvc
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKGRS_DYNAMIC: 1
install:
  # install OpenSSL
  - mkdir C:\OpenSSL
  - appveyor DownloadFile https://curl.haxx.se/ca/cacert.pem -FileName C:\OpenSSL\cacert.pem

  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V
build: false
test_script:
  - cargo build --verbose --all
  - cargo test --verbose --all
branches:
  only:
    - master