[package]
name = "graph-core"
version = "0.2.0"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Common types for the graph-rs project"

[dependencies]
Inflector = "0.11.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.21", features = ["derive"] }
